area:content:
  - changed-files:
      - any-glob-to-any-file:
          - 'd1/migrations/**'
          - 'apps/serp.software/lib/submissions/**'
          - 'apps/pornvideodownloaders.com/lib/submissions/**'
          - 'd1/publications/**'
